CREATE TABLE TYPE_CARTE
(
   CODE_TYPE_CARTE 		INT NOT NULL AUTO_INCREMENT, 
   LIBELLE_TYPE_CRATE	VARCHAR(50),
   PLF_GLO_PAIE			DECIMAL,
   PLF_GLO_PAIE_ETRG	DECIMAL,
   PERI_PLF_PAIE		INT,
   PLF_GLO_RET_EXT		DECIMAL,
   PLF_RET_ETRG			DECIMAL,
   PLF_RET_FCE			DECIMAL,
   PERI_PLF_GLO_RET		INT,
   PLF_GLO_RET_INT		DECIMAL,
   PRIMARY KEY ( CODE_TYPE_CARTE )
) COMMENT = 'Référentiel des type de carte';

CREATE TABLE CLIENT(
   NUMERO_CLI 	INT NOT NULL AUTO_INCREMENT,
   NOM 			VARCHAR(100) NOT NULL,
   PRENOM 		VARCHAR(40) NOT NULL,
   DT_NAISS 	DATE NOT NULL,
   EMAIL 		VARCHAR(100) NOT NULL,
   ADRESSE_PRINC 	VARCHAR(100),	 
   ADRESSE_TEMP 	VARCHAR(100),
   TEL_FIXE 	VARCHAR(20),
   TEL_PRTABLE 	VARCHAR(20),
   PRIMARY KEY ( NUMERO_CLI )
) COMMENT = 'Table des clients ';

CREATE TABLE COMPTE(
   NUMERO_COMPTE 	INT NOT NULL AUTO_INCREMENT,   
   DT_OUVERTURE 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   MONTANT_INITIAL	DECIMAL,
   NUMERO_CLI		INT NOT NULL,
   TYPE_COMPTE		VARCHAR(50) NOT NULL,
   PRIMARY KEY ( NUMERO_COMPTE )
) COMMENT = 'Table des comptes bancaires des clients';  

CREATE TABLE OPERATION(
   REFERENCE 		INT NOT NULL AUTO_INCREMENT,   
   LIBELLE 			VARCHAR(100) NOT NULL,
   TYPE_OPERATION	VARCHAR(30),
   NUMERO_COMPTE	INT NOT NULL,
   DT_COMPTABLE		DATE,
   DT_OPERATION		DATE,
   DT_VALEUR		DATE,
   MNT_DEBIT		DECIMAL,
   MNT_CREDIT		DECIMAL,
   STATUT			VARCHAR(30),  
   MOYEN_PAIEMENT	VARCHAR(30),
   PRIMARY KEY ( REFERENCE )
) COMMENT = 'Table des transactions effectuées sur un compte'; 

CREATE TABLE CHEQUIER(
   NUMERO_CHQ 		INT NOT NULL AUTO_INCREMENT,   
   NOMBRE_CHQ		INT,
   NUMERO_1_CHQ		VARCHAR(30),
   NUMERO_D_CHQ		VARCHAR(30),
   PRIMARY KEY ( NUMERO_CHQ )
)COMMENT = 'Table des chéquiers associés aux comptes bancaires';

CREATE TABLE CARTE_BANCAIRE(
   NUMERO_CARTE 	VARCHAR(16) NOT NULL,
   DT_DEB_VALIDITE	DATE  NOT NULL,
   DT_FIN_VALIDITE	DATE  NOT NULL,
   RESEAU_CARTE		VARCHAR(10)  NOT NULL,
   CODE_TYPE_CARTE	INT  NOT NULL,
   PRIMARY KEY ( NUMERO_CARTE )
)COMMENT = 'Table des cartes bancaires associées aux comptes bancaires';


CREATE TABLE HISTO_ETUDIANT(
   REFERENCE_HISTO	INT NOT NULL AUTO_INCREMENT,
   ANNEE_ACADEMIQUE	VARCHAR(9) NOT NULL,
   DIPLOME_PREPA	VARCHAR(30),
   NIVEAU_ETUDE		VARCHAR(30),
   NUMERO_CLI		INT NOT NULL,   
   PRIMARY KEY ( REFERENCE_HISTO )
)COMMENT = 'Table d''historiques pour un client étudiant';

CREATE TABLE PRODUIT(
   CODE_PRODUIT		INT NOT NULL AUTO_INCREMENT,
   LIBELLE_PRODUIT	VARCHAR(100) NOT NULL,  
   PRIMARY KEY ( CODE_PRODUIT )
)COMMENT = 'Référentiel des produits commercialisés';


CREATE TABLE CONTRAT(
	NUMERO_CTR			INT NOT NULL AUTO_INCREMENT,
	DT_SOUS				DATE NOT NULL,
    INTITULE			VARCHAR(100),	
    NUMERO_CLI			INT,
	CODE_PRODUIT		INT,
	NUMERO_COMPTE		INT,
	STATUT_JUR			VARCHAR(30),
	PRIMARY KEY ( NUMERO_CTR )
)COMMENT = 'Table des contrats souscrits par des clients';

CREATE TABLE CONTRAT_CREDIT(
	NUMERO_CTR			INT NOT NULL,
	OBJ_CREDIT			VARCHAR(100),
    DT_SOUS				DATE,
    DT_ECHEANCE			DATE NOT NULL,
	DUREE				INT NOT NULL,
	TAUX				DECIMAL,
	MNT_CREDIT			DECIMAL NOT NULL,
	STATUT_JUR_CLIENT	VARCHAR(30),
	DT_PROC_ECHANCE		DATE,
	MNT_ECHEANCE		DECIMAL,
	TAUX_NOMINAL		DECIMAL,
	ENCOURS				DECIMAL,
	PRIMARY KEY ( NUMERO_CTR )
)COMMENT = 'Table des crédits souscrits par des clients';

CREATE TABLE CONTRAT_EPARGNE(
	NUMERO_CTR			INT NOT NULL,
	TYPE_EPARGNE		VARCHAR(30),
    TYPE_VERSEMENT		VARCHAR(30),
    PERIODICITE			VARCHAR(30),
	DT_VERSEMENT		DATE,	
	MNT_VERSE			DECIMAL NOT NULL,	
	PRIMARY KEY ( NUMERO_CTR )
)COMMENT = 'Table des contrats sur produits épargne souscrits par des clients';
